collections:
  - education
  - experience

theme: jekyll-theme-cayman

title: Joe Irving
email: joe@bicycle.ga
description: CV
url: joe.irving.me.uk

repository: joe-irving/joe-irving.github.io

permalink: pretty
