collections:
  education:
    sort_by: start
  experience:
    sort_by: start

theme: jekyll-theme-cayman
title: Joe Irving
email: joe@bicycle.ga
description: >-
  CV
url: "joe.irving.me.uk"

permalink: pretty
